version: "3.2"
services: 
    reverse-proxy: 
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./reverse-proxy
        ports: 
            - "3050:80"
        networks:
            - app-network
        hostname: reverse-proxy
        container_name: synctune_reverse_proxy
        depends_on: 
            - "signalling-server"
            - "client"
    signalling-server:
        build: 
            dockerfile: Dockerfile.dev
            context: ./signalling-server
        volumes: 
            - /app/node_modules
            - ./signalling-server:/app
        environment: 
            - SOCKET_IO_PATH=socket.io
        networks:
            - app-network
        hostname: signalling-server
        container_name: synctune_signalling_server
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - VUE_APP_SIGNALLING_SERVER_SOCKET_IO_PATH=signalling-server/socket.io
        networks: 
            - app-network
        hostname: client
        container_name: synctune_client
    redis:
        image: redis
        networks: 
            - app-network
networks:
    app-network: