version: "3.2"
services:
    reverse-proxy:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./reverse-proxy
        ports:
            - "3050:80"
        networks:
            - app-network
        hostname: reverse-proxy
        container_name: synctune_reverse_proxy
        depends_on:
            - "room-server"
            - "client"
    room-server:
        build:
            dockerfile: Dockerfile.dev
            context: ./room-server
        volumes:
            - /app/node_modules
            - ./room-server:/app
        environment:
            - SOCKET_IO_PATH=socket.io
        networks:
            - app-network
        hostname: room-server
        container_name: synctune_room_server
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - VUE_APP_ROOM_SERVER_URL=/room-server
            - VUE_APP_ROOM_SERVER_SOCKET_IO_PATH=room-server/socket.io # TODO: remove this
        networks:
            - app-network
        hostname: client
        container_name: synctune_client
    redis:
        image: redis
        networks:
            - app-network
networks:
    app-network:
